Feature/lp2922 lp2924-Accessiblity changes
BEIS-Digital-Services/htg-learning-platform pull request #111
Opened 2022-07-18 14:55 UTC by venkatrangala

2022-07-18 14:59 UTC, thomaslkp123 approved these changes

2022-07-18 16:55 UTC, jdssunil submitted a review, later dismissed

2022-07-18 16:57 UTC, thomaslkp123 submitted a review, later dismissed

2022-07-19 08:21 UTC, emailtokvk approved these changes

2022-07-26 08:33 UTC, JamesChristianson requested changes

2022-07-26 08:33 UTC, JamesChristianson commented on Beis.LearningPlatform.Web/Views/Shared/Components/CmsSocialMedia/Default.cshtml
> +            $('#close').attr('tabIndex', -1);
j query

2022-07-28 09:22 UTC, thomaslkp123 approved these changes

2022-08-02 14:21 UTC, thomaslkp123 commented on Beis.LearningPlatform.Web/Views/Shared/Components/CmsSocialMedia/Default.cshtml
> +            $('#close').attr('tabIndex', -1);
outdated

2022-08-02 15:35 UTC, TasTasniem approved these changes

2022-08-02 15:35 UTC, JamesChristianson approved these changes

2022-08-02 15:45 UTC, jdssunil approved these changes

2022-08-03 15:11 UTC, thomaslkp123 approved these changes

2022-08-03 15:12 UTC, thomaslkp123 commented
Nothing left to merge

2022-08-03 15:12 UTC, closed without merging