Feature/lp 2935 keyboard onclick alternative
BEIS-Digital-Services/htg-learning-platform pull request #115
Opened 2022-07-19 13:48 UTC by thomaslkp123

2022-07-26 08:28 UTC, JamesChristianson commented on Beis.LearningPlatform.Web/Views/Shared/Components/CmsSocialMedia/Default.cshtml
> +            $('#copy').attr('tabIndex', -1);
Remove jquery please

2022-07-26 08:32 UTC, JamesChristianson requested changes

2022-07-26 08:32 UTC, JamesChristianson commented on Beis.LearningPlatform.Web/Views/Shared/Components/CmsSocialMedia/Default.cshtml
> +            $('#copy').attr('tabIndex', -1);
remove jq plz

2022-07-28 09:12 UTC, kelechi-i submitted a review, later dismissed
Tested successfully on QA

2022-07-28 10:01 UTC, emailtokvk approved these changes

2022-07-28 10:13 UTC, thomaslkp123 commented on Beis.LearningPlatform.Web/Views/Shared/Components/CmsSocialMedia/Default.cshtml
> +            $('#copy').attr('tabIndex', -1);
removed

2022-07-28 10:13 UTC, thomaslkp123 commented on Beis.LearningPlatform.Web/Views/Shared/Components/CmsSocialMedia/Default.cshtml
> +            $('#copy').attr('tabIndex', -1);
removed

2022-07-28 10:23 UTC, kelechi-i approved these changes

2022-07-28 10:55 UTC, JamesChristianson approved these changes

2022-07-28 10:55 UTC, merged