Release 27 back to main
BEIS-Digital-Services/htg-learning-platform pull request #130
Opened 2022-07-26 08:31 UTC by thomaslkp123

2022-07-26 08:34 UTC, JamesChristianson requested changes

2022-07-26 08:34 UTC, JamesChristianson commented on Beis.LearningPlatform.DAL/ExpressionOfInterestDataService.cs
> +            var entity = _mapper.Map<ExpressionOfInterest>(expressionOfInterestDto);
Auto mapper - must be removed

2022-07-26 08:51 UTC, JamesChristianson requested changes

2022-07-26 08:51 UTC, JamesChristianson commented on Beis.LearningPlatform.DAL/ExpressionOfInterestDataService.cs
> +            var entity = _mapper.Map<ExpressionOfInterest>(expressionOfInterestDto);
Remove automapper code

2022-07-27 15:12 UTC, JamesChristianson approved these changes

2022-07-27 15:27 UTC, emailtokvk approved these changes

2022-07-28 08:26 UTC, merged