lp-3276 Implement caption type in textblock and textwithimage
BEIS-Digital-Services/htg-learning-platform pull request #186
Opened 2022-08-15 12:17 UTC by TasTasniem

2022-08-15 13:51 UTC, thomaslkp123 submitted a review, later dismissed

2022-08-16 13:11 UTC, emailtokvk requested changes

2022-08-16 13:11 UTC, emailtokvk commented on Beis.LearningPlatform.Web/Models/ImageWithTextViewModel.cs
> +                    if (_cmsPageComponent.CaptionType == "SpecificCaption")
can we have enum?

2022-08-16 13:50 UTC, jdssunil submitted a review, later dismissed

2022-08-17 08:16 UTC, TasTasniem commented on Beis.LearningPlatform.Web/Models/ImageWithTextViewModel.cs
> +                    if (_cmsPageComponent.CaptionType == "SpecificCaption")
Made the change

2022-08-17 08:34 UTC, emailtokvk approved these changes

2022-08-17 14:41 UTC, rajchala approved these changes
Tested in QA

2022-08-17 14:51 UTC, merged